### ISSUE TITLE
PullRequest Event

### ISSUE THREAD

**Issue by bobboteck** [bobboteck/Widget_GitHub_Organization#2]
Acttualy is not managed
![image](https://cloud.githubusercontent.com/assets/5130571/6865659/524f2e8c-d470-11e4-8d49-fe6aa97bdc14.png)

**Comment by rbonghi** [comment]
Yes I have this problem on my webpage with flame icon:
![screen shot 2015-04-13 at 15 42 47](https://cloud.githubusercontent.com/assets/4551246/7116710/ed99f85a-e1f3-11e4-8a1c-cbc299b55b61.png)

**Comment by bobboteck** [comment]
You can read the event, not actualy supported, on tooltip over the flame icon.
I think you see an "Issue Comment Event", actualy another issue is open for it https://github.com/bobboteck/Widget_GitHub_Organization/issues/4

**Comment by bobboteck** [comment]
Added pull request basic manage
